name: Record a test1

on:
  workflow_dispatch: 

jobs:
  record-stream:
    runs-on: ubuntu-latest

    env:
      tag_name: recording-${{ github.run_id }}

    steps:
      - name: disable initramfs
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
      - name: disable man-db
        run: sudo rm -f /var/lib/man-db/auto-update
      - name: Configure fast APT mirror
        uses: vegardit/fast-apt-mirror.sh@v1
        with: 
              exclude-current: true
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mpv ffmpeg yt-dlp

      - name: mpv
        id: record
        continue-on-error: true
        run: |
          mkdir -p artifact/out
          mpv --vo=null --ao=null "https://video.detik.com/trans7/smil:trans7.smil/chunklist_w577694934_b744100_sleng.m3u8" --referrer="https://20.detik.com/" --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36" --http-header-fields="Origin: https://20.detik.com" --stream-record=artifact/out/recorded.ts
          # mpv --vo=null --ao=null "https://live.eu-north-1b.cf.dmcdn.net/sec2(SPAM50G8_vK5G-DtubVD_RxSAUWVPJ7RcpxgdbZ1Iu6BPoFvlPQ07f5fX4iHBZlCxZ59q1kuSBVSJyV65bMmLvIHYJepcdyGFvqIoHBZ2O2rvvYzQ1Q92weLbFh7JQuV)/dm/3/x8qckyq/d/live-720.m3u8" --stream-record=artifact/out/recorded.ts

      - name: ts to mp4
        if: always()
        run: |
          if [ -f artifact/out/recorded.ts ]; then
            ffmpeg -i artifact/out/recorded.ts -vcodec copy -acodec copy artifact/out/recorded.mp4
            rm -rf artifact/out/recorded.ts 
          else
            echo "recorded.ts not found"
          fi

      - name: create release
        if: always()
        run: |
          gh release create "$tag_name" --repo "${{ github.repository }}" \
            --title "1🌈🌈🌈 - $tag_name" \
            --notes "1🌈🌈🌈" \
            --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload artifacts to the release
        if: always()
        run: |
          repo=${{ github.repository }}
          tag_name=${{ env.tag_name }}
          for artifact_dir in ./artifact/*; do
            for artifact in "$artifact_dir"/*; do
              gh release upload "$tag_name" "$artifact" --repo "$repo" --clobber
            done
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup (optional)
        if: always()
        run: rm -rf artifact
