name: DL

on:
  workflow_dispatch: 

jobs:
  record-stream:
    runs-on: ubuntu-latest

    env:
      tag_name: recording-${{ github.run_id }}

    steps:
      - name: disable initramfs
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
      - name: disable man-db
        run: sudo rm -f /var/lib/man-db/auto-update
      - name: Configure fast APT mirror
        uses: vegardit/fast-apt-mirror.sh@v1
        with: 
              exclude-current: true
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mpv ffmpeg yt-dlp wget aria2

      - name: mpv
        id: record
        run: |
          mkdir -p artifact/out

      - name: ts to mp4
        if: always()
        run: |
            cd artifact/out/
            aria2c 'https://upaste.de/raw/tUS'
            aria2c -i tUS

      - name: create release
        run: |
          gh release create "$tag_name" --repo "${{ github.repository }}" \
            --title "DL - $tag_name" \
            --notes "DL" \
            --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload artifacts to the release
        run: |
          repo=${{ github.repository }}
          tag_name=${{ env.tag_name }}
          for artifact_dir in ./artifact/*; do
            for artifact in "$artifact_dir"/*; do
              gh release upload "$tag_name" "$artifact" --repo "$repo" --clobber
            done
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup (optional)
        if: always()
        run: rm -rf artifact
